name: HideNSeek
version: '${project.version}'
main: hidenseek.hidenseek.HideNSeek
api-version: 1.17
authors: [ kortsu22 ]
commands:
  startgame:
    usage: /<command>
    description: Starts a Hide and Seek match
  setseekersspawn:
    usage: /<command>
    description: Sets the spawn for the seekers
  sethidersspawn:
    usage: /<command>
    description: Sets the spawn for the hiders
  stopgame:
    usage: /<command>
    description: Stops a Hide and Seek match
  timeremaining:
    usage: /<command>
    description: Gives you the remaining time of the Hide and Seek game
